// Arduino Code Generator — Blockly v10+ (CodeGenerator / forBlock API)
// Blockly v10+ replaced Blockly.Generator with Blockly.CodeGenerator
// and changed block generator registration from generator['type'] to generator.forBlock['type']

function defineArduinoGenerator() {
  // ─── Create the generator (Blockly v13 uses Blockly.CodeGenerator) ───────
  // Support both old (Generator) and new (CodeGenerator) APIs
  const GeneratorClass = Blockly.CodeGenerator || Blockly.Generator;

  if (!Blockly.Arduino) {
    Blockly.Arduino = new GeneratorClass('Arduino');
  }

  // Ensure forBlock exists (it always does in v10+, but safety net for v8)
  if (!Blockly.Arduino.forBlock) {
    Blockly.Arduino.forBlock = Object.create(null);
  }

  // Helper: register a generator on BOTH the instance AND forBlock
  // This makes the generator compatible with Blockly v8, v9, v10, v11, v13
  const reg = (type, fn) => {
    Blockly.Arduino.forBlock[type] = fn;
    Blockly.Arduino[type] = fn; // backward compat
  };

  // ─── Operator Precedence Constants ────────────────────────────────────────
  Blockly.Arduino.ORDER_ATOMIC         = 0;   // literals, identifiers
  Blockly.Arduino.ORDER_UNARY_POSTFIX  = 1;   // expr++, expr--, ()
  Blockly.Arduino.ORDER_FUNCTION_CALL  = 1;   // foo()
  Blockly.Arduino.ORDER_UNARY_PREFIX   = 2;   // ++expr, --expr, +expr, -expr, !
  Blockly.Arduino.ORDER_MULTIPLICATIVE = 3;   // * / %
  Blockly.Arduino.ORDER_MODULUS        = 3;   // %
  Blockly.Arduino.ORDER_ADDITIVE       = 4;   // + -
  Blockly.Arduino.ORDER_BITWISE_SHIFT  = 5;   // << >>
  Blockly.Arduino.ORDER_RELATIONAL     = 6;   // < <= > >=
  Blockly.Arduino.ORDER_EQUALITY       = 7;   // == !=
  Blockly.Arduino.ORDER_BITWISE_AND    = 8;   // &
  Blockly.Arduino.ORDER_BITWISE_XOR    = 9;   // ^
  Blockly.Arduino.ORDER_BITWISE_OR     = 10;  // |
  Blockly.Arduino.ORDER_LOGICAL_AND    = 11;  // &&
  Blockly.Arduino.ORDER_LOGICAL_OR     = 12;  // ||
  Blockly.Arduino.ORDER_CONDITIONAL    = 13;  // ? :
  Blockly.Arduino.ORDER_ASSIGNMENT     = 14;  // =
  Blockly.Arduino.ORDER_COMMA          = 15;  // ,
  Blockly.Arduino.ORDER_NONE           = 99;  // no precedence

  // ─── Generator Lifecycle: init / scrub_ / finish ──────────────────────────
  Blockly.Arduino.init = function(workspace) {
    this.isInitialized = true;
    this.definitions_  = Object.create(null);
    this.functionNames_ = Object.create(null);
    this.setups_       = Object.create(null);
    this.loops_        = Object.create(null);
    this.pins_         = Object.create(null);

    // Variable name database
    if (!this.nameDB_) {
      this.nameDB_ = new Blockly.Names(this.RESERVED_WORDS_ || '');
    } else {
      this.nameDB_.reset();
    }
    this.nameDB_.setVariableMap(workspace.getVariableMap
      ? workspace.getVariableMap()
      : (workspace.variableMap_ || null));
  };

  // scrub_ chains sequential statements
  Blockly.Arduino.scrub_ = function(block, code, opt_thisOnly) {
    const nextBlock = block.nextConnection && block.nextConnection.targetBlock();
    const nextCode  = opt_thisOnly ? '' : this.blockToCode(nextBlock);
    return code + nextCode;
  };

  // finish assembles the complete Arduino sketch
  Blockly.Arduino.finish = function(code) {
    const indent = (str) => {
      if (!str) return '';
      return str.split('\n')
        .map(line => line.trim() ? '  ' + line : line)
        .join('\n')
        .replace(/\n{3,}/g, '\n\n');
    };

    const includes     = [];
    const globalDefs   = [];

    for (const name in this.definitions_) {
      const def = this.definitions_[name];
      if (!def || typeof def !== 'string') continue;
      if (def.trim().startsWith('#include')) {
        includes.push(def.trim());
      } else {
        globalDefs.push(def.trim());
      }
    }

    // Collect setup lines: pin modes first, then user setup code
    const setupLines = [];
    for (const pin in this.pins_) {
      setupLines.push(this.pins_[pin]);
    }
    for (const name in this.setups_) {
      const s = this.setups_[name];
      if (s && s.trim()) setupLines.push(s.trim());
    }

    // Collect loop lines
    const loopLines = [];
    for (const name in this.loops_) {
      const l = this.loops_[name];
      if (l && l.trim()) loopLines.push(l.trim());
    }
    if (code && code.trim()) {
      loopLines.push(code.trim());
    }

    let result = '// Generated by IrieBlocky\n\n';

    if (includes.length > 0) {
      result += includes.join('\n') + '\n\n';
    }
    if (globalDefs.length > 0) {
      result += globalDefs.join('\n') + '\n\n';
    }

    result += 'void setup() {\n';
    if (setupLines.length > 0) {
      result += indent(setupLines.join('\n')) + '\n';
    } else {
      result += '  // Put setup code here, to run once:\n';
    }
    result += '}\n\n';

    result += 'void loop() {\n';
    if (loopLines.length > 0) {
      result += indent(loopLines.join('\n')) + '\n';
    } else {
      result += '  // Put main code here, to run repeatedly:\n';
    }
    result += '}\n';

    return result;
  };

  // ─── Standard Blockly Generators (Control, Logic, Math, Text, Vars) ───────

  reg('controls_if', function(block, gen) {
    let n = 0, code = '';
    do {
      const cond   = gen.valueToCode(block, 'IF' + n, gen.ORDER_NONE) || 'false';
      const branch = gen.statementToCode(block, 'DO' + n);
      code += (n > 0 ? ' else if (' : 'if (') + cond + ') {\n' + branch + '}';
      n++;
    } while (block.getInput('IF' + n));
    if (block.getInput('ELSE')) {
      code += ' else {\n' + gen.statementToCode(block, 'ELSE') + '}';
    }
    return code + '\n';
  });

  reg('controls_repeat_ext', function(block, gen) {
    const times  = gen.valueToCode(block, 'TIMES', gen.ORDER_ADDITIVE) || '0';
    const branch = gen.statementToCode(block, 'DO');
    return 'for (int i = 0; i < ' + times + '; i++) {\n' + branch + '}\n';
  });

  reg('controls_whileUntil', function(block, gen) {
    const until = block.getFieldValue('MODE') === 'UNTIL';
    let cond = gen.valueToCode(block, 'BOOL',
      until ? gen.ORDER_LOGICAL_AND : gen.ORDER_NONE) || 'false';
    if (until) cond = '!' + cond;
    return 'while (' + cond + ') {\n' + gen.statementToCode(block, 'DO') + '}\n';
  });

  reg('logic_compare', function(block, gen) {
    const OPS = { EQ:'==', NEQ:'!=', LT:'<', LTE:'<=', GT:'>', GTE:'>=' };
    const op = OPS[block.getFieldValue('OP')] || '==';
    const a  = gen.valueToCode(block, 'A', gen.ORDER_RELATIONAL) || '0';
    const b  = gen.valueToCode(block, 'B', gen.ORDER_RELATIONAL) || '0';
    return [a + ' ' + op + ' ' + b, gen.ORDER_RELATIONAL];
  });

  reg('logic_operation', function(block, gen) {
    const isAnd = block.getFieldValue('OP') === 'AND';
    const op    = isAnd ? '&&' : '||';
    const order = isAnd ? gen.ORDER_LOGICAL_AND : gen.ORDER_LOGICAL_OR;
    const a     = gen.valueToCode(block, 'A', order) || 'false';
    const b     = gen.valueToCode(block, 'B', order) || 'false';
    return [a + ' ' + op + ' ' + b, order];
  });

  reg('logic_negate', function(block, gen) {
    const arg = gen.valueToCode(block, 'BOOL', gen.ORDER_UNARY_PREFIX) || 'true';
    return ['!' + arg, gen.ORDER_UNARY_PREFIX];
  });

  reg('logic_boolean', function(block, gen) {
    return [block.getFieldValue('BOOL') === 'TRUE' ? 'true' : 'false', gen.ORDER_ATOMIC];
  });

  reg('logic_null', function(block, gen) {
    return ['NULL', gen.ORDER_ATOMIC];
  });

  reg('math_number', function(block, gen) {
    const num = parseFloat(block.getFieldValue('NUM'));
    return [isNaN(num) ? '0' : String(num), gen.ORDER_ATOMIC];
  });

  reg('math_arithmetic', function(block, gen) {
    const OPS = {
      ADD:      [' + ',  gen.ORDER_ADDITIVE],
      MINUS:    [' - ',  gen.ORDER_ADDITIVE],
      MULTIPLY: [' * ',  gen.ORDER_MULTIPLICATIVE],
      DIVIDE:   [' / ',  gen.ORDER_MULTIPLICATIVE],
      POWER:    [null,   gen.ORDER_NONE]
    };
    const [op, order] = OPS[block.getFieldValue('OP')] || [' + ', gen.ORDER_ADDITIVE];
    const a = gen.valueToCode(block, 'A', order) || '0';
    const b = gen.valueToCode(block, 'B', order) || '0';
    if (!op) return ['pow(' + a + ', ' + b + ')', gen.ORDER_UNARY_POSTFIX];
    return [a + op + b, order];
  });

  reg('math_single', function(block, gen) {
    const operator = block.getFieldValue('OP');
    if (operator === 'NEG') {
      const arg = gen.valueToCode(block, 'NUM', gen.ORDER_UNARY_PREFIX) || '0';
      return ['-' + arg, gen.ORDER_UNARY_PREFIX];
    }
    const arg = gen.valueToCode(block, 'NUM', gen.ORDER_NONE) || '0';
    const MAP = {
      ABS:'abs(', ROOT:'sqrt(', LN:'log(', EXP:'exp(',
      POW10:'pow(10, ', ROUND:'round(', ROUNDUP:'ceil(', ROUNDDOWN:'floor(',
      SIN:'sin(', COS:'cos(', TAN:'tan('
    };
    const fn = MAP[operator];
    if (fn) {
      if (operator === 'POW10') return ['pow(10, ' + arg + ')', gen.ORDER_UNARY_POSTFIX];
      return [fn + arg + ')', gen.ORDER_UNARY_POSTFIX];
    }
    return [arg, gen.ORDER_ATOMIC];
  });

  reg('text', function(block, gen) {
    return [JSON.stringify(block.getFieldValue('TEXT') || ''), gen.ORDER_ATOMIC];
  });

  reg('text_join', function(block, gen) {
    if (!block.itemCount_) return ['""', gen.ORDER_ATOMIC];
    if (block.itemCount_ === 1) {
      const el = gen.valueToCode(block, 'ADD0', gen.ORDER_UNARY_POSTFIX) || '""';
      return ['String(' + el + ')', gen.ORDER_UNARY_POSTFIX];
    }
    const parts = [];
    for (let i = 0; i < block.itemCount_; i++) {
      parts.push('String(' + (gen.valueToCode(block, 'ADD' + i, gen.ORDER_NONE) || '""') + ')');
    }
    return [parts.join(' + '), gen.ORDER_ADDITIVE];
  });

  reg('text_length', function(block, gen) {
    const v = gen.valueToCode(block, 'VALUE', gen.ORDER_UNARY_POSTFIX) || '""';
    return ['String(' + v + ').length()', gen.ORDER_UNARY_POSTFIX];
  });

  reg('variables_get', function(block, gen) {
    const varName = gen.nameDB_
      ? gen.nameDB_.getName(block.getFieldValue('VAR'), Blockly.Names.NameType.VARIABLE)
      : block.getFieldValue('VAR');
    return [varName, gen.ORDER_ATOMIC];
  });

  reg('variables_set', function(block, gen) {
    const varName = gen.nameDB_
      ? gen.nameDB_.getName(block.getFieldValue('VAR'), Blockly.Names.NameType.VARIABLE)
      : block.getFieldValue('VAR');
    const value = gen.valueToCode(block, 'VALUE', gen.ORDER_ASSIGNMENT) || '0';
    gen.definitions_['var_' + varName] = 'long ' + varName + ' = 0;';
    return varName + ' = ' + value + ';\n';
  });

  reg('procedures_defnoreturn', function(block, gen) {
    const name   = block.getFieldValue('NAME');
    const branch = gen.statementToCode(block, 'STACK');
    gen.definitions_['func_' + name] = 'void ' + name + '() {\n' + branch + '}\n';
    return null;
  });

  reg('procedures_defreturn', function(block, gen) {
    const name   = block.getFieldValue('NAME');
    const branch = gen.statementToCode(block, 'STACK');
    const ret    = gen.valueToCode(block, 'RETURN', gen.ORDER_NONE) || '';
    const retStr = ret ? '  return ' + ret + ';\n' : '';
    gen.definitions_['func_' + name] = 'int ' + name + '() {\n' + branch + retStr + '}\n';
    return null;
  });

  reg('procedures_callnoreturn', function(block, gen) {
    return block.getFieldValue('NAME') + '();\n';
  });

  reg('procedures_callreturn', function(block, gen) {
    return [block.getFieldValue('NAME') + '()', gen.ORDER_UNARY_POSTFIX];
  });

  // ─── Arduino Core Blocks ──────────────────────────────────────────────────

  reg('serial_begin', function(block, gen) {
    const baud = block.getFieldValue('BAUD');
    gen.setups_['serial_begin'] = 'Serial.begin(' + baud + ');';
    return '';
  });

  reg('delay_ms', function(block, gen) {
    return 'delay(' + block.getFieldValue('MS') + ');\n';
  });

  reg('wait_ms', function(block, gen) {
    return 'delay(' + block.getFieldValue('MS') + ');\n';
  });

  reg('millis', function(block, gen) {
    return ['millis()', gen.ORDER_FUNCTION_CALL];
  });

  reg('wait_forever', function(block, gen) {
    return 'while (true) {}\n';
  });

  // arduino_setup: collects statements → stores in setups_
  reg('arduino_setup', function(block, gen) {
    const stmts = gen.statementToCode(block, 'SETUP_STATEMENTS');
    if (stmts && stmts.trim()) {
      gen.setups_['user_setup'] = stmts.trim();
    }
    return ''; // content is in finish()
  });

  // arduino_loop: collects statements → stores in loops_
  reg('arduino_loop', function(block, gen) {
    const stmts = gen.statementToCode(block, 'LOOP_STATEMENTS');
    if (stmts && stmts.trim()) {
      gen.loops_['user_loop'] = stmts.trim();
    }
    return ''; // content is in finish()
  });

  // ─── Digital / Analog I/O ─────────────────────────────────────────────────

  reg('digital_write', function(block, gen) {
    const pin   = block.getFieldValue('PIN');
    const state = block.getFieldValue('STATE');
    gen.pins_[pin] = 'pinMode(' + pin + ', OUTPUT);';
    return 'digitalWrite(' + pin + ', ' + state + ');\n';
  });

  reg('pwm_write', function(block, gen) {
    const pin   = block.getFieldValue('PIN');
    const value = block.getFieldValue('VALUE');
    gen.pins_[pin] = 'pinMode(' + pin + ', OUTPUT);';
    return 'analogWrite(' + pin + ', ' + value + ');\n';
  });

  reg('digital_read', function(block, gen) {
    const pin = block.getFieldValue('PIN');
    gen.pins_[pin] = 'pinMode(' + pin + ', INPUT);';
    return ['digitalRead(' + pin + ')', gen.ORDER_ATOMIC];
  });

  reg('analog_read', function(block, gen) {
    const pin = block.getFieldValue('PIN');
    return ['analogRead(' + pin + ')', gen.ORDER_ATOMIC];
  });

  reg('led_write', function(block, gen) {
    const state = block.getFieldValue('STATE');
    gen.pins_['LED_BUILTIN'] = 'pinMode(LED_BUILTIN, OUTPUT);';
    return 'digitalWrite(LED_BUILTIN, ' + state + ');\n';
  });

  reg('tone_start', function(block, gen) {
    const pin  = block.getFieldValue('PIN');
    const freq = block.getFieldValue('FREQ');
    return 'tone(' + pin + ', ' + freq + ');\n';
  });

  reg('tone_stop', function(block, gen) {
    return 'noTone(' + block.getFieldValue('PIN') + ');\n';
  });

  // ─── Sensors ──────────────────────────────────────────────────────────────

  reg('sensor_temp', function(block, gen) {
    const unit = block.getFieldValue('UNIT');
    return ['readTemperature("' + unit + '")', gen.ORDER_FUNCTION_CALL];
  });

  reg('light_sensor', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    return ['map(analogRead(' + pin + '), 0, 1023, 0, 100)', gen.ORDER_FUNCTION_CALL];
  });

  reg('light_sensor_raw', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    return ['analogRead(' + pin + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('potentiometer', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    return ['analogRead(' + pin + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('ultrasonic_add', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'sonar';
    const trig  = block.getFieldValue('TRIG_PIN') || '9';
    const echo  = block.getFieldValue('ECHO_PIN') || '10';
    gen.definitions_['inc_newping'] = '#include <NewPing.h>';
    gen.definitions_['var_' + name] = 'NewPing ' + name + '(' + trig + ', ' + echo + ', 200);';
    return '';
  });

  reg('ultrasonic_read', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'sonar';
    return [name + '.ping_cm()', gen.ORDER_FUNCTION_CALL];
  });

  reg('encoder_add', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'enc';
    const pinA = block.getFieldValue('PIN_A') || '2';
    const pinB = block.getFieldValue('PIN_B') || '3';
    gen.definitions_['inc_encoder'] = '#include <Encoder.h>';
    gen.definitions_['var_' + name] = 'Encoder ' + name + '(' + pinA + ', ' + pinB + ');';
    return '';
  });

  reg('encoder_read', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'enc';
    return [name + '.read()', gen.ORDER_FUNCTION_CALL];
  });

  reg('encoder_write', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'enc';
    const value = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '0';
    return name + '.write(' + value + ');\n';
  });

  reg('color_sensor_color', function(block, gen) {
    const channel = block.getFieldValue('CHANNEL') || 'RED';
    return ['readColor("' + channel + '")', gen.ORDER_FUNCTION_CALL];
  });

  reg('color_sensor_brightness', function(block, gen) {
    return ['readBrightness()', gen.ORDER_FUNCTION_CALL];
  });

  reg('color_sensor_lux', function(block, gen) {
    return ['readLux()', gen.ORDER_FUNCTION_CALL];
  });

  reg('color_sensor_temp', function(block, gen) {
    return ['readColorTemp()', gen.ORDER_FUNCTION_CALL];
  });

  reg('distance_sensor_mm', function(block, gen) {
    return ['readDistanceMM()', gen.ORDER_FUNCTION_CALL];
  });

  reg('mpu6050_accel', function(block, gen) {
    const axis = block.getFieldValue('AXIS') || 'X';
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_mpu'] = '#include <MPU6050.h>';
    gen.setups_['mpu6050_init'] = 'Wire.begin();\n  MPU6050_Init();';
    return ['readAccel' + axis + '()', gen.ORDER_FUNCTION_CALL];
  });

  reg('mpu6050_gyro', function(block, gen) {
    const axis = block.getFieldValue('AXIS') || 'X';
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_mpu'] = '#include <MPU6050.h>';
    gen.setups_['mpu6050_init'] = 'Wire.begin();\n  MPU6050_Init();';
    return ['readGyro' + axis + '()', gen.ORDER_FUNCTION_CALL];
  });

  reg('rtc_add', function(block, gen) {
    gen.definitions_['inc_rtc'] = '#include <RTClib.h>';
    gen.definitions_['var_rtc'] = 'RTC_DS1307 rtc;';
    gen.setups_['rtc_begin'] = 'rtc.begin();';
    return '';
  });

  reg('rtc_year', function(block, gen) {
    return ['rtc.now().year()', gen.ORDER_FUNCTION_CALL];
  });

  reg('rtc_get', function(block, gen) {
    const field = block.getFieldValue('FIELD') || 'HOUR';
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_rtc'] = '#include <RTClib.h>';
    gen.definitions_['var_rtc'] = 'RTC_DS1307 rtc;';
    gen.setups_['rtc_begin'] = 'Wire.begin();\n  rtc.begin();';
    const methodMap = {
      HOUR: 'hour()',
      MINUTE: 'minute()',
      SECOND: 'second()',
      DAY: 'day()',
      MONTH: 'month()',
      YEAR: 'year()'
    };
    return ['rtc.now().' + (methodMap[field] || 'hour()'), gen.ORDER_FUNCTION_CALL];
  });

  reg('dht_init', function(block, gen) {
    const pin = block.getFieldValue('PIN') || '2';
    const model = block.getFieldValue('MODEL') || 'DHT22';
    gen.definitions_['inc_dht'] = '#include "DHT.h"';
    gen.definitions_['var_dht'] = `DHT dht(${pin}, ${model});`;
    gen.setups_['dht_begin'] = 'dht.begin();';
    return '';
  });

  reg('dht_read_temp', function(block, gen) {
    const unit = block.getFieldValue('UNIT') || 'C';
    gen.definitions_['inc_dht'] = '#include "DHT.h"';
    return [`dht.readTemperature(${unit === 'F' ? 'true' : 'false'})`, gen.ORDER_FUNCTION_CALL];
  });

  reg('dht_read_humidity', function(block, gen) {
    gen.definitions_['inc_dht'] = '#include "DHT.h"';
    return ['dht.readHumidity()', gen.ORDER_FUNCTION_CALL];
  });

  reg('pir_read_motion', function(block, gen) {
    const pin = block.getFieldValue('PIN') || '2';
    gen.pins_[pin] = `pinMode(${pin}, INPUT);`;
    return [`(digitalRead(${pin}) == HIGH)`, gen.ORDER_RELATIONAL];
  });

  reg('ldr_read_level', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    const unit = block.getFieldValue('UNIT') || 'PERCENT';
    if (unit === 'PERCENT') {
      return [`map(analogRead(${pin}), 0, 1023, 0, 100)`, gen.ORDER_FUNCTION_CALL];
    }
    return [`analogRead(${pin})`, gen.ORDER_FUNCTION_CALL];
  });

  reg('mq2_read_gas', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    const mode = block.getFieldValue('MODE') || 'ANALOG';
    if (mode === 'DIGITAL') {
      gen.pins_[pin] = `pinMode(${pin}, INPUT);`;
      return [`digitalRead(${pin})`, gen.ORDER_FUNCTION_CALL];
    }
    return [`analogRead(${pin})`, gen.ORDER_FUNCTION_CALL];
  });

  reg('ntc_read_temp', function(block, gen) {
    const pin = block.getFieldValue('PIN') || 'A0';
    const unit = block.getFieldValue('UNIT') || 'C';
    gen.definitions_['func_readNTC'] =
`float readNTC(int pin) {
  int raw = analogRead(pin);
  float v = raw * (5.0 / 1023.0);
  float r = (5.0 - v) * 10000.0 / v;
  return 1.0 / (1.0 / 298.15 + (1.0 / 3950.0) * log(r / 10000.0)) - 273.15;
}`;
    if (unit === 'F') {
      return [`(readNTC(${pin}) * 1.8 + 32.0)`, gen.ORDER_MULTIPLICATIVE];
    }
    return [`readNTC(${pin})`, gen.ORDER_FUNCTION_CALL];
  });

  reg('ds18b20_read_temp', function(block, gen) {
    const pin = block.getFieldValue('PIN') || '2';
    const unit = block.getFieldValue('UNIT') || 'C';
    gen.definitions_['inc_onewire'] = '#include <OneWire.h>';
    gen.definitions_['inc_dallas'] = '#include <DallasTemperature.h>';
    gen.definitions_['var_onewire_' + pin] = `OneWire oneWire_${pin}(${pin});\nDallasTemperature sensors_${pin}(&oneWire_${pin});`;
    gen.setups_['dallas_' + pin] = `sensors_${pin}.begin();`;
    if (unit === 'F') {
      return [`(sensors_${pin}.requestTemperatures(), sensors_${pin}.getTempFByIndex(0))`, gen.ORDER_COMMA];
    }
    return [`(sensors_${pin}.requestTemperatures(), sensors_${pin}.getTempCByIndex(0))`, gen.ORDER_COMMA];
  });

  reg('bmp180_read_pressure', function(block, gen) {
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_bmp'] = '#include <Adafruit_BMP085.h>';
    gen.definitions_['var_bmp'] = 'Adafruit_BMP085 bmp;';
    gen.setups_['bmp_begin'] = 'Wire.begin();\n  bmp.begin();';
    return ['(bmp.readPressure() / 100.0F)', gen.ORDER_MULTIPLICATIVE];
  });

  reg('bmp180_read_temp', function(block, gen) {
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_bmp'] = '#include <Adafruit_BMP085.h>';
    gen.definitions_['var_bmp'] = 'Adafruit_BMP085 bmp;';
    gen.setups_['bmp_begin'] = 'Wire.begin();\n  bmp.begin();';
    return ['bmp.readTemperature()', gen.ORDER_FUNCTION_CALL];
  });

  reg('bmp180_read_altitude', function(block, gen) {
    gen.definitions_['inc_wire'] = '#include <Wire.h>';
    gen.definitions_['inc_bmp'] = '#include <Adafruit_BMP085.h>';
    gen.definitions_['var_bmp'] = 'Adafruit_BMP085 bmp;';
    gen.setups_['bmp_begin'] = 'Wire.begin();\n  bmp.begin();';
    return ['bmp.readAltitude()', gen.ORDER_FUNCTION_CALL];
  });

  reg('hx711_init', function(block, gen) {
    const dout = block.getFieldValue('DOUT') || '2';
    const sck = block.getFieldValue('SCK') || '3';
    gen.definitions_['inc_hx711'] = '#include "HX711.h"';
    gen.definitions_['var_hx711'] = `HX711 scale;`;
    gen.setups_['hx711_begin'] = `scale.begin(${dout}, ${sck});\n  scale.set_scale(2280.f);\n  scale.tare();`;
    return '';
  });

  reg('hx711_read_weight', function(block, gen) {
    const unit = block.getFieldValue('UNIT') || 'G';
    gen.definitions_['inc_hx711'] = '#include "HX711.h"';
    if (unit === 'KG') {
      return ['(scale.get_units(5) / 1000.0)', gen.ORDER_MULTIPLICATIVE];
    }
    return ['scale.get_units(5)', gen.ORDER_FUNCTION_CALL];
  });

  reg('mfrc522_init', function(block, gen) {
    const ss = block.getFieldValue('SS') || '10';
    const rst = block.getFieldValue('RST') || '9';
    gen.definitions_['inc_spi'] = '#include <SPI.h>';
    gen.definitions_['inc_mfrc522'] = '#include <MFRC522.h>';
    gen.definitions_['var_mfrc522'] = `MFRC522 rfid(${ss}, ${rst});`;
    gen.setups_['mfrc522_begin'] = 'SPI.begin();\n  rfid.PCD_Init();';
    return '';
  });

  reg('mfrc522_card_present', function(block, gen) {
    gen.definitions_['inc_spi'] = '#include <SPI.h>';
    gen.definitions_['inc_mfrc522'] = '#include <MFRC522.h>';
    return ['rfid.PICC_IsNewCardPresent()', gen.ORDER_FUNCTION_CALL];
  });

  reg('mfrc522_read_uid', function(block, gen) {
    gen.definitions_['inc_spi'] = '#include <SPI.h>';
    gen.definitions_['inc_mfrc522'] = '#include <MFRC522.h>';
    return ['String(rfid.uid.uidByte[0], HEX)', gen.ORDER_FUNCTION_CALL];
  });

  reg('joystick_read', function(block, gen) {
    const axis = block.getFieldValue('AXIS') || 'X';
    const pin = block.getFieldValue('PIN') || 'A0';
    if (axis === 'BTN') {
      gen.pins_[pin] = `pinMode(${pin}, INPUT_PULLUP);`;
      return [`(digitalRead(${pin}) == LOW)`, gen.ORDER_RELATIONAL];
    }
    return [`analogRead(${pin})`, gen.ORDER_FUNCTION_CALL];
  });

  // ─── Motion: Servo, Stepper, DC Motor ─────────────────────────────────────

  reg('motion_move', function(block, gen) {
    return 'move(' + block.getFieldValue('DISTANCE') + ');\n';
  });

  reg('servo_attach', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'myServo';
    const pin  = block.getFieldValue('PIN')  || '9';
    gen.definitions_['inc_servo'] = '#include <Servo.h>';
    gen.definitions_['var_' + name] = 'Servo ' + name + ';';
    gen.setups_['servo_' + name] = name + '.attach(' + pin + ');';
    return '';
  });

  reg('servo_detach', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'myServo';
    return name + '.detach();\n';
  });

  reg('servo_write', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'myServo';
    const angle = gen.valueToCode(block, 'ANGLE', gen.ORDER_ATOMIC) || block.getFieldValue('ANGLE') || '90';
    return name + '.write(' + angle + ');\n';
  });

  reg('servo_read', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'myServo';
    return [name + '.read()', gen.ORDER_FUNCTION_CALL];
  });

  reg('stepper_create_2pin', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'myStepper';
    const steps = block.getFieldValue('STEPS') || '200';
    const p1    = block.getFieldValue('PIN1') || '8';
    const p2    = block.getFieldValue('PIN2') || '9';
    gen.definitions_['inc_stepper'] = '#include <Stepper.h>';
    gen.definitions_['var_' + name] = 'Stepper ' + name + '(' + steps + ', ' + p1 + ', ' + p2 + ');';
    return '';
  });

  reg('stepper_create_4pin', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'myStepper';
    const steps = block.getFieldValue('STEPS') || '200';
    const pins  = [
      block.getFieldValue('PIN1') || '8',
      block.getFieldValue('PIN2') || '9',
      block.getFieldValue('PIN3') || '10',
      block.getFieldValue('PIN4') || '11'
    ];
    gen.definitions_['inc_stepper'] = '#include <Stepper.h>';
    gen.definitions_['var_' + name] = 'Stepper ' + name + '(' + steps + ', ' + pins.join(', ') + ');';
    return '';
  });

  reg('stepper_set_speed', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'myStepper';
    const speed = block.getFieldValue('SPEED') || '60';
    return name + '.setSpeed(' + speed + ');\n';
  });

  reg('stepper_step', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'myStepper';
    const steps = gen.valueToCode(block, 'STEPS', gen.ORDER_ATOMIC) || block.getFieldValue('STEPS') || '100';
    return name + '.step(' + steps + ');\n';
  });

  reg('l298n_attach', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'motor';
    const ena  = block.getFieldValue('ENA_PIN') || '5';
    const in1  = block.getFieldValue('IN1_PIN') || '6';
    const in2  = block.getFieldValue('IN2_PIN') || '7';
    gen.pins_[ena] = 'pinMode(' + ena + ', OUTPUT);';
    gen.pins_[in1] = 'pinMode(' + in1 + ', OUTPUT);';
    gen.pins_[in2] = 'pinMode(' + in2 + ', OUTPUT);';
    gen.definitions_['var_' + name + '_ena'] = 'const int ' + name + '_ENA = ' + ena + ';';
    gen.definitions_['var_' + name + '_in1'] = 'const int ' + name + '_IN1 = ' + in1 + ';';
    gen.definitions_['var_' + name + '_in2'] = 'const int ' + name + '_IN2 = ' + in2 + ';';
    return '';
  });

  reg('l298n_set_direction', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'motor';
    const dir  = block.getFieldValue('DIRECTION') || 'FORWARD';
    if (dir === 'FORWARD') {
      return 'digitalWrite(' + name + '_IN1, HIGH);\ndigitalWrite(' + name + '_IN2, LOW);\n';
    } else if (dir === 'BACKWARD') {
      return 'digitalWrite(' + name + '_IN1, LOW);\ndigitalWrite(' + name + '_IN2, HIGH);\n';
    }
    return 'digitalWrite(' + name + '_IN1, LOW);\ndigitalWrite(' + name + '_IN2, LOW);\n';
  });

  reg('l298n_set_speed', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'motor';
    const speed = gen.valueToCode(block, 'SPEED', gen.ORDER_ATOMIC) || '150';
    return 'analogWrite(' + name + '_ENA, ' + speed + ');\n';
  });

  // ─── Math Extensions ──────────────────────────────────────────────────────

  reg('math_map', function(block, gen) {
    const value    = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '0';
    const fromLow  = block.getFieldValue('FROM_LOW');
    const fromHigh = block.getFieldValue('FROM_HIGH');
    const toLow    = block.getFieldValue('TO_LOW');
    const toHigh   = block.getFieldValue('TO_HIGH');
    return ['map(' + value + ', ' + fromLow + ', ' + fromHigh + ', ' + toLow + ', ' + toHigh + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_sin', function(block, gen) {
    const angle = gen.valueToCode(block, 'ANGLE', gen.ORDER_ATOMIC) || '0';
    return ['sin(' + angle + ' * PI / 180.0)', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_pi', function(block, gen) {
    return ['PI', gen.ORDER_ATOMIC];
  });

  reg('math_is_even', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_MULTIPLICATIVE) || '0';
    return ['(' + num + ' % 2 == 0)', gen.ORDER_RELATIONAL];
  });

  reg('math_round', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_NONE) || '0';
    return ['round(' + num + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_sqrt', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_NONE) || '0';
    return ['sqrt(' + num + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_min', function(block, gen) {
    const a = gen.valueToCode(block, 'A', gen.ORDER_NONE) || '0';
    const b = gen.valueToCode(block, 'B', gen.ORDER_NONE) || '0';
    return ['min(' + a + ', ' + b + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_modulo', function(block, gen) {
    const a = gen.valueToCode(block, 'DIVIDEND', gen.ORDER_MULTIPLICATIVE) || '0';
    const b = gen.valueToCode(block, 'DIVISOR', gen.ORDER_MULTIPLICATIVE) || '1';
    return [a + ' % ' + b, gen.ORDER_MULTIPLICATIVE];
  });

  reg('math_constrain', function(block, gen) {
    const val  = gen.valueToCode(block, 'VALUE', gen.ORDER_NONE) || '0';
    const low  = gen.valueToCode(block, 'LOW', gen.ORDER_NONE) || '0';
    const high = gen.valueToCode(block, 'HIGH', gen.ORDER_NONE) || '255';
    return ['constrain(' + val + ', ' + low + ', ' + high + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_map_advanced', function(block, gen) {
    const value    = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '0';
    const fromLow  = gen.valueToCode(block, 'FROM_LOW', gen.ORDER_ATOMIC) || '0';
    const fromHigh = gen.valueToCode(block, 'FROM_HIGH', gen.ORDER_ATOMIC) || '1023';
    const toLow    = gen.valueToCode(block, 'TO_LOW', gen.ORDER_ATOMIC) || '0';
    const toHigh   = gen.valueToCode(block, 'TO_HIGH', gen.ORDER_ATOMIC) || '255';
    return ['map(' + value + ', ' + fromLow + ', ' + fromHigh + ', ' + toLow + ', ' + toHigh + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_random_int', function(block, gen) {
    const min = gen.valueToCode(block, 'FROM', gen.ORDER_ATOMIC) || '0';
    const max = gen.valueToCode(block, 'TO', gen.ORDER_ATOMIC) || '100';
    return ['random(' + min + ', ' + max + ' + 1)', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_random_float', function(block, gen) {
    return ['(random(0, 10000) / 10000.0)', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_bit_read', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_ATOMIC) || '0';
    const bit = gen.valueToCode(block, 'BIT', gen.ORDER_ATOMIC) || '0';
    return ['bitRead(' + num + ', ' + bit + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('math_bit_clear', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_ATOMIC) || '0';
    const bit = gen.valueToCode(block, 'BIT', gen.ORDER_ATOMIC) || '0';
    return 'bitClear(' + num + ', ' + bit + ');\n';
  });

  reg('math_bit_write', function(block, gen) {
    const num   = gen.valueToCode(block, 'NUM', gen.ORDER_ATOMIC) || '0';
    const bit   = gen.valueToCode(block, 'BIT', gen.ORDER_ATOMIC) || '0';
    const value = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '0';
    return 'bitWrite(' + num + ', ' + bit + ', ' + value + ');\n';
  });

  reg('math_high_byte', function(block, gen) {
    const num = gen.valueToCode(block, 'NUM', gen.ORDER_ATOMIC) || '0';
    return ['highByte(' + num + ')', gen.ORDER_FUNCTION_CALL];
  });

  // ─── Signal Processing ────────────────────────────────────────────────────

  reg('signal_new_filter', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'filter';
    const size = block.getFieldValue('SIZE') || '5';
    gen.definitions_['var_' + name] = 'MovingAverage ' + name + '(' + size + ');';
    return '';
  });

  reg('signal_add_to_filter', function(block, gen) {
    const name  = block.getFieldValue('NAME') || 'filter';
    const value = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '0';
    return name + '.add(' + value + ');\n';
  });

  reg('signal_get_filter_value', function(block, gen) {
    const name = block.getFieldValue('NAME') || 'filter';
    return [name + '.get()', gen.ORDER_FUNCTION_CALL];
  });

  // ─── String / Text Extensions ─────────────────────────────────────────────

  reg('char_is_alpha', function(block, gen) {
    const c = gen.valueToCode(block, 'CHAR', gen.ORDER_ATOMIC) || '"a"';
    return ['isAlpha(' + c + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_starts_with', function(block, gen) {
    const str    = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    const prefix = gen.valueToCode(block, 'PREFIX', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').startsWith(' + prefix + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_to_upper', function(block, gen) {
    const str = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').toUpperCase()', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_to_int', function(block, gen) {
    const str = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').toInt()', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_create', function(block, gen) {
    const val = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '""';
    return ['String(' + val + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_append', function(block, gen) {
    const str = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    const val = gen.valueToCode(block, 'VALUE', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ') + String(' + val + ')', gen.ORDER_ADDITIVE];
  });

  reg('string_find', function(block, gen) {
    const str    = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    const substr = gen.valueToCode(block, 'SUBSTRING', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').indexOf(' + substr + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_substring', function(block, gen) {
    const str   = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    const start = gen.valueToCode(block, 'START', gen.ORDER_ATOMIC) || '0';
    const end   = gen.valueToCode(block, 'END', gen.ORDER_ATOMIC) || '0';
    return ['String(' + str + ').substring(' + start + ', ' + end + ')', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_trim', function(block, gen) {
    const str = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').trim()', gen.ORDER_FUNCTION_CALL];
  });

  reg('string_replace', function(block, gen) {
    const str    = gen.valueToCode(block, 'STRING', gen.ORDER_ATOMIC) || '""';
    const target = gen.valueToCode(block, 'TARGET', gen.ORDER_ATOMIC) || '""';
    const repl   = gen.valueToCode(block, 'REPLACEMENT', gen.ORDER_ATOMIC) || '""';
    return ['String(' + str + ').replace(' + target + ', ' + repl + ')', gen.ORDER_FUNCTION_CALL];
  });
}
